enable-magisk-update = true
patches-version = "v4.10.1-dev.1"
integrations-version = "v1.11.1-dev.1"


[YouTube]
app-name = "YouTube"
build-mode = "both"
version = "auto"
included-patches = "'Remove player controls background' 'Custom branding' 'Enable slide to seek'"
excluded-patches = "'Enable debugging' 'Announcements'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"

[Music]
build-mode = "both"
version = "auto"
included-patches = "'Hide category bar' 'Permanent shuffle' 'Permanent repeat'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
arch = "arm64-v8a"
included-patches = "'Open links with app chooser'"