enable-magisk-update = true
patches-version = "v4.10.0-dev.10"
integrations-version = "v1.11.0-dev.7"


[YouTube]
app-name = "YouTube"
build-mode = "both"
version = "auto"
included-patches = "'Remove player controls background' 'Enable slide to seek'"
excluded-patches = "'Announcements' 'Enable debugging'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"

[Music]
# enabled = false
build-mode = "both"
version = "auto"
included-patches = "'Hide category bar' 'Permanent shuffle' 'Permanent repeat'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
arch = "arm64-v8a"
included-patches = "'Open links with app chooser'"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
arch = "arm64-v8a"
build-mode = "both"
apkmirror-arch = "arm64-v8a"