enable-magisk-update = true
patches-version = "v4.12.0-dev.11"
integrations-version = "v1.12.0-dev.6"


[YouTube]
build-mode = "both"
version = "auto"
included-patches = "'Remove player controls background' 'Enable slide to seek'"
excluded-patches = "'Disable zoom haptics' 'Enable debugging' 'Announcements' 'Disable rolling number animations'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"

[Music]
build-mode = "both"
version = "auto"
included-patches = "'Hide category bar' 'Permanent shuffle' 'Permanent repeat'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
arch = "arm64-v8a"
included-patches = "'Open links with app chooser'"