enable-magisk-update = true
# patches-version = "v4.8.0-dev.23"
# integrations-version = "v1.9.0-dev.14"


[YouTube]
app-name = "YouTube"
build-mode = "both"
version = "auto"
included-patches = "'Remove player controls background' 'Enable slide to seek'"
excluded-patches = "'Announcements' 'Enable debugging'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"

[Music]
# enabled = false
build-mode = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
included-patches = "'Open links with app chooser'"
