enable-magisk-update = true
# patches-version = "v4.13.4-dev.2"
# integrations-version = "v1.13.1-dev.2"


[YouTube]
build-mode = "both"
version = "auto"
included-patches = "'Remove player controls background' 'Custom branding' 'Enable slide to seek'"
excluded-patches = "'Announcements' 'Enable debugging'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"

[Music]
build-mode = "both"
version = "auto"
included-patches = "'Hide category bar' 'Permanent shuffle' 'Permanent repeat'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/x-corp/twitter/"
arch = "arm64-v8a"
included-patches = "'Open links with app chooser'"