enable-magisk-update = true
patches-version = "v4.14.2-dev.2"
integrations-version = "v1.14.2-dev.2"


[YouTube]
build-mode = "both"
version = "auto"
included-patches = "'Remove player controls background' 'Custom branding' 'Enable slide to seek'"
excluded-patches = "'Announcements' 'Enable debugging'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
apkmirror-arch = "arm64-v8a"

[Music]
build-mode = "both"
version = "auto"
included-patches = "'Hide category bar' 'Permanent shuffle' 'Permanent repeat'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
apkmirror-arch = "arm64-v8a"

[Twitter]
build-mode = "apk"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
included-patches = "'Open links with app chooser'"